### ISSUE TITLE
Code review / best practices

### ISSUE THREAD

**Issue by oddforms-design** [oddforms-design/Dongled#3]
I am a self-taught coder and would be happy to have someone look at the code to identify issues that might not conform with best practice. Identify other issues that might stand out to someone else not self-taught or with more advanced swift level.

**Comment by trysightdev** [comment]
Code looks good.
Function and classes are named well so no need for long comments and documentation.
UI is modulized and the managers are portable and scalable.
Only problem I had was that I wasn't able to build it because I had unsupported version of XCode.
So just add the minimum requirements to build the source.

**Comment by oddforms-design** [comment]
Thanks for taking a look. Yes I think the set xcode version is required as it needs iPadOS 17 or newer, I'll add a note.
